function createOccupationFractionFigure(X1, Y1, Y2, YNeg1, YPos1,labelsIn)
%CREATEFIGURE(X1, Y1, Y2, YNEG1, YPOS1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  errorbar y vector data
%  YNEG1:  errorbar ynegativedelta vector data
%  YPOS1:  errorbar ypositivedelta vector data

%  Auto-generated by MATLAB on 18-Dec-2022 21:52:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[1 0 0],'Marker','diamond','LineWidth',3,...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create errorbar
errorbar(X1,Y2,YNeg1,YPos1,'MarkerSize',4,'MarkerFaceColor',[0 0 0],...
    'Marker','o',...
    'LineStyle','none',...
    'LineWidth',3,...
    'Color',[0 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.5 3.5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',25,'FontWeight','bold','LineWidth',3,'XTick',[1 2 3],...
    'XTickLabel',labelsIn);
