function createInPoleFig(X1, Y2, y2min, y2max,lw,labelsIn,xTit,xTicksIn,color1,color2,color3)



% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

[d0,d1,d2]=errorBarCustom(X1(1),Y2(1),y2min(1),y2max(1),lw)
set(d0,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','.','LineWidth',2.5,...
    'LineStyle','none',...
    'DisplayName','sim',...
    'Color',color1)
set(d1,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','none','LineWidth',2.5,...
    'LineStyle','-',...
    'DisplayName','sim',...
    'Color',color1)

set(d2,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','none','LineWidth',2.5,...
    'LineStyle','-',...
    'DisplayName','sim',...
    'Color',color1)

[d0,d1,d2]=errorBarCustom(X1(2),Y2(2),y2min(2),y2max(2),lw)
set(d0,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','.','LineWidth',2.5,...
    'LineStyle','none',...
    'DisplayName','sim',...
    'Color',color2)
set(d1,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','none','LineWidth',2.5,...
    'LineStyle','-',...
    'DisplayName','sim',...
    'Color',color2)

set(d2,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','none','LineWidth',2.5,...
    'LineStyle','-',...
    'DisplayName','sim',...
    'Color',color2)


[d0,d1,d2]=errorBarCustom(X1(3),Y2(3),y2min(3),y2max(3),lw)
set(d0,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','.','LineWidth',2.5,...
    'LineStyle','none',...
    'DisplayName','sim',...
    'Color',color3)
set(d1,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','none','LineWidth',2.5,...
    'LineStyle','-',...
    'DisplayName','sim',...
    'Color',color3)

set(d2,'MarkerSize',25,'MarkerFaceColor','none',...
    'Marker','none','LineWidth',2.5,...
    'LineStyle','-',...
    'DisplayName','sim',...
    'Color',color3)
% %

%%



% Create xlabel
xlabel(xTit);

% Create title
title({''});

% Create ylabel
ylabel({'% In pole'});

xlim(axes1,[X1(1)-5, X1(3)+5])
ylim(axes1,[0 30]);

box(axes1,'on');
% Set the remaining axes properties
% set(axes1,'FontName','Cambria','FontSize',25,'FontWeight','bold','LineWidth',3,'XTick',X1,...
%    'XTickLabel',labelsIn);

set(axes1,'FontName','Cambria','FontSize',25,'LineWidth',3,'XTick',xTicksIn,'YTick',0:5:30,...
    'XTickLabel',labelsIn);

x0=10;
y0=10;
width=400;
height=400;
axis square
%set(gcf,'units','points','position',[x0,y0,width,height])
